name: "Static Analysis"

on:
  push:
    branches:
      - master
      - '*.x'

  pull_request:

  schedule:
    - cron: '0 0 * * *'

jobs:
  static-analysis-phpstan:

    name: Source Code
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, memcached, oci8
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run Static Analysis
        run: vendor/bin/phpstan
